# Generated by Django 4.2.3 on 2023-07-29 13:47

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='receiver_user',
            field=models.ForeignKey(on_delete=models.SET(django.contrib.auth.models.AnonymousUser), related_name='receiver', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='message',
            name='sender_user',
            field=models.ForeignKey(on_delete=models.SET(django.contrib.auth.models.AnonymousUser), related_name='sender', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='room',
            name='receiver_user',
            field=models.ForeignKey(on_delete=models.SET(django.contrib.auth.models.AnonymousUser), related_name='room_receiver', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='room',
            name='sender_user',
            field=models.ForeignKey(on_delete=models.SET(django.contrib.auth.models.AnonymousUser), related_name='room_sender', to=settings.AUTH_USER_MODEL),
        ),
    ]
